import ReactiveSecondFormGroupCurrencyArea from "./reactiveSecondFormGroupCurrencyArea";

let InitializationSecondReactiveFormForCurrency=new ReactiveSecondFormGroupCurrencyArea
export default InitializationSecondReactiveFormForCurrency.formSecondInputGroupCurrency
