import ReactiveFormGroupCurrencyArea from "./reactiveFormGroupCurrencyArea";

let InitializationReactiveFormForCurrency=new ReactiveFormGroupCurrencyArea
export default InitializationReactiveFormForCurrency.formInputGroupCurrency

